/*
* Given two strings s and t which consist of only lowercase letters.
* String t is generated by random shuffling string s and then add one more letter at a random position.
* Find the letter that was added in t.
*/
public static char findTheDifference(String s, String t) {
        StringBuilder strBuilder = new StringBuilder(s);
        strBuilder.append(t);
        char a = 0;
        System.out.println(strBuilder);
        for(int i = strBuilder.length() - 1; i >= 0; i--) {
            a ^= strBuilder.charAt(i);
        }
        return a;
    }
